on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run ergogen
        run: yarn ergogen ergogen.yaml
      - name: Run openjscad to make the plate
        run: yarn run openjscad -o output/cases/plate.stl output/cases/plate.jscad
      - name: Run openjscad to make the base
        run: yarn run openjscad -o output/cases/base.stl output/cases/base.jscad
      - name: Persist output
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: output